#!/usr/bin/env bash

set -e
set -u

script_name="$(basename "${0}")"
script_dir="$(realpath "$(dirname "${0}")")"
script_usage="${script_name} DOMAIN"

usage() {
  echo "${script_name}: usage: ${script_usage}" >&2
}

exit_with_error() {
  echo "${script_name}: error: ${1}" >&2
  usage
  exit 1
}

recieved_arguments="${#}"
expected_arguments="1"

if [ "${recieved_arguments}" != "${expected_arguments}" ]; then
  exit_with_error "invalid number of arguments, expected \"${expected_arguments}\", recieved \"${recieved_arguments}\""
fi

domain="${1}"

if ! "${script_dir}/validate-domain" "${domain}"; then
  exit_with_error "not a valid domain '${domain}'"
fi

cat <<EOF
server {
  listen 80;
  listen [::]:80;

  server_name ${domain};

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }
}
EOF
