#!/usr/bin/env bash
script_name="$0"
script_dir="$(realpath "$(dirname "$0")")"
docker_compose_dir="$(realpath "$script_dir/..")"
docker_compose_filepath="$docker_compose_dir/docker-compose.yml"

if ! "$script_dir/nginx-test"; then
  exit 1
fi

docker-compose -f "$docker_compose_filepath" exec nginx nginx -s reload
