#!/usr/bin/env bash

set -e
set -u

script_name="$(basename "${0}")"
script_dir="$(realpath "$(dirname "${0}")")"
script_usage="${script_name} USERNAME PASSWORD"

usage() {
  echo "${script_name}: usage: ${script_usage}" >&2
}

exit_with_error() {
  echo "${script_name}: error: ${1}" >&2
  usage
  exit 1
}

recieved_arguments="${#}"
expected_arguments="2"

if [ "${recieved_arguments}" != "${expected_arguments}" ]; then
  exit_with_error "invalid number of arguments, expected \"${expected_arguments}\", recieved \"${recieved_arguments}\""
fi

username="${1}"
password="${2}"

root_dir="$(realpath "${script_dir}/..")"
htpasswd_file="${root_dir}/nginx/htpasswd"

docker run --rm --entrypoint htpasswd httpd:2 -Bbn "${username}" "${password}" | sed '/^$/d' >>"${htpasswd_file}"
