#!/usr/bin/env bash

script_name="$(basename "$0")"

usage() {
  echo "$script_name: usage: $script_name REGEX VALUE" >&2
}

exit_with_error() {
  echo "$script_name: error: $1" >&2
  usage
  exit 1
}

if [ "$#" != "2" ]; then
  exit_with_error "invalid number of arguments $#"
fi

regex="$1"
value="$2"

if [[ ! "$value" =~ $regex ]]; then
  exit_with_error "value '$value' failed to match pattern '$regex'"
fi

exit 0
