#!/usr/bin/env bash

set -e
set -u

script_name="$(basename "$0")"
script_dir="$(realpath "$(dirname "$0")")"

usage() {
  echo "$script_name: usage: $script_name EMAIL" >&2
}

exit_with_error() {
  echo "$script_name: error: $1" >&2
  usage
  exit 1
}

if [ "$#" != "1" ]; then
  exit_with_error "invalid number of arguments $#"
fi

validate_regex="$script_dir/validate-regex"
regex_email="^[a-z0-9+_.-]+@[a-z0-9.-]+$"
email="$1"

if ! "$validate_regex" "$regex_email" "$email"; then
  exit_with_error "not a valid email '$email'"
fi
