#!/usr/bin/env bash

set -e
set -u

script_name="$(basename "${0}")"
script_dir="$(realpath "$(dirname "${0}")")"

usage() {
  echo "${script_name}: usage: ${script_name} HTTP_URL" >&2
}

exit_with_error() {
  echo "${script_name}: error: ${1}" >&2
  usage
  exit 1
}

if [ "${#}" != "1" ]; then
  exit_with_error "invalid number of arguments ${#}"
fi

validate_regex="${script_dir}/validate-regex"
regex_url="^https?://[^ ]+$"
url="${1}"

if ! "${validate_regex}" "${regex_url}" "${url}"; then
  exit_with_error "not a valid url '${url}'"
fi
